CREATE PROCEDURE `avg_prix` (vd VARCHAR(30),va VARCHAR(30),OUT moy_prix DOUBLE)
SELECT avg(COVOITURAGE.PRIX) INTO moy_prix
FROM TRAJET_TYPE,COVOITURAGE
WHERE VILLE_DEPART = vd AND VILLE_ARRIVEE = va AND VILLE_DEPART = V_DEPART AND VILLE_ARRIVEE = V_ARRIVEE;
