/*
mysql -h venus -u fvielmas fvielmas -p
Fichier tables.sql
21507569, Bourdeau, Clement
20130265, Vielmas, Florent
*/

DROP TABLE AVIS;
DROP TABLE INSCRIPTION;
DROP TABLE COVOITURAGE;
DROP TABLE TRAJET_TYPE;
DROP TABLE VEHICULE;
DROP TABLE MEMBRE;


CREATE TABLE MEMBRE(
       ID INT AUTO_INCREMENT,
       PTYPE VARCHAR(15) CHECK (PTYPE IN ('ADMINISTRATEUR','UTILISATEUR')),
       EMAIL VARCHAR(40),
       MDP VARCHAR(20),
       NOM VARCHAR(40),
       PRENOM VARCHAR(40),
       DATE_NAISSANCE DATE,
       ADRESSE VARCHAR(500),
       TEL NUMERIC(10),
       VEHICULE VARCHAR(10),
       CONSTRAINT PK_MEMBRE PRIMARY KEY (ID) 
       );

CREATE TABLE VEHICULE(
       PLAQUE VARCHAR(10),
       MARQUE VARCHAR(20),
       MODELE VARCHAR(20),
       NBPLACES INT,
       CONSTRAINT PK_VEHICULE PRIMARY KEY (PLAQUE) 
       );

CREATE TABLE TRAJET_TYPE(
       VILLE_DEPART VARCHAR(30),
       VILLE_ARRIVEE VARCHAR(30),
       TPS_MOYEN INT,
       PRIX DOUBLE,
       CONSTRAINT PK_TRAJET_TYPE PRIMARY KEY (VILLE_DEPART,VILLE_ARRIVEE)
       );

CREATE TABLE COVOITURAGE(
       NUMCOVOIT INT AUTO_INCREMENT,
       V_DEPART VARCHAR(30),
       V_ARRIVEE VARCHAR(30),
       PRIX DOUBLE,
       DUREE INT,
       CONDUCTEUR INT,
       DATE_D DATE,
       H_DEPART INT,
       H_ARRIVE INT,
       RDV VARCHAR(30),
       DEPOSE VARCHAR(30),
       NBPASSAGERS NUMERIC(1),
       NB_PLACES_DISPO NUMERIC(1),
       CONSTRAINT PK_COVOITURAGE PRIMARY KEY (NUMCOVOIT),
       CONSTRAINT FK_COVOITURAGE_CONDUCTUER FOREIGN KEY(CONDUCTEUR) REFERENCES MEMBRE(ID)
       );

CREATE TABLE INSCRIPTION(
       MEMBRE INT,
       TRAJET INT,
       CONSTRAINT FK_INSCRIPTION_MEMBRE FOREIGN KEY(MEMBRE) REFERENCES MEMBRE(ID),
       CONSTRAINT FK_INSCRIPTION_TRAJET FOREIGN KEY(TRAJET) REFERENCES COVOITURAGE(NUMCOVOIT)
       );

CREATE TABLE AVIS(
       ID_COND INT,
       ID_PASSAGER INT,
       NOTE INT,
       CONSTRAINT FK_AVIS_ID_CONDUCTEUR FOREIGN KEY(ID_COND) REFERENCES MEMBRE(ID),
       CONSTRAINT FK_AVIS_ID_PASSAGER FOREIGN KEY(ID_PASSAGER) REFERENCES MEMBRE(ID)
       );
    


