DROP TRIGGER `covoit_trajet_type`;
CREATE TRIGGER `covoit_trajet_type` 
BEFORE INSERT ON `COVOITURAGE` FOR EACH ROW
INSERT INTO TRAJET_TYPE (VILLE_DEPART,VILLE_ARRIVEE) VALUES (NEW.V_DEPART,NEW.V_ARRIVEE);
