/*
mysql -h venus -u fvielmas fvielmas -p
Fichier: covoit_trajet_type.sql
21507569, Bourdeau, Clement
20130265, Vielmas, Florent
*/

DROP TRIGGER IF EXISTS `covoit_trajet_type`;
DELIMITER |
CREATE TRIGGER `covoit_trajet_type` AFTER INSERT ON `COVOITURAGE`
FOR EACH ROW IF NEW.V_DEPART NOT IN(SELECT VILLE_DEPART FROM TRAJET_TYPE) AND NEW.V_ARRIVEE NOT IN (SELECT VILLE_ARRIVEE FROM TRAJET_TYPE) 
THEN INSERT INTO TRAJET_TYPE (VILLE_DEPART,VILLE_ARRIVEE,TPS_MOYEN,PRIX) VALUES (NEW.V_DEPART,NEW.V_ARRIVEE,NEW.DUREE,NEW.PRIX);
END IF;
|

DELIMITER ;


/*
Ce que tu avais fait a la base si jamais ça ne marchait plus

DROP TRIGGER `covoit_trajet_type`;
CREATE TRIGGER `covoit_trajet_type` 
AFTER INSERT ON `COVOITURAGE` FOR EACH ROW
INSERT INTO TRAJET_TYPE (VILLE_DEPART,VILLE_ARRIVEE,TPS_MOYEN,PRIX) VALUES (NEW.V_DEPART,NEW.V_ARRIVEE,NEW.DUREE,NEW.PRIX);
*/


