/*
mysql -h venus -u fvielmas fvielmas -p
Fichier : update_nbplaces.sql
21507569, Bourdeau, Clement
20130265, Vielmas, Florent
*/

DROP TRIGGER IF EXISTS `update_nbplaces`;
DELIMITER |
CREATE TRIGGER `update_nbplaces` BEFORE INSERT ON `INSCRIPTION`
FOR EACH ROW
UPDATE COVOITURAGE
SET NB_PLACES_DISPO = IF(NB_PLACES_DISPO > 0,NB_PLACES_DISPO - 1,NB_PLACES_DISPO) 
WHERE COVOITURAGE.NUMCOVOIT = NEW.TRAJET;
|

DELIMITER ;
